apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev
  namespace: argocd
spec:
  description: Dev environment project

  sourceRepos:
    - https://github.com/tekne-ops/gitops-platform
    - https://github.com/tekne-ops/gitops-platform.git

  destinations:
    - server: https://kubernetes.default.svc
      namespace: devops-lab
    - server: https://kubernetes.default.svc
      namespace: cert-manager
    - server: https://kubernetes.default.svc
      namespace: monitoring

  namespaceResourceWhitelist:
    - group: apps
      kind: Deployment
    - group: '*'
      kind: '*'

  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
