apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev
  namespace: argocd
spec:
  description: development

  sourceRepos:
    - '*'

  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
