helmGlobals:
  chartHome: /tmp/helmcharts

helmCharts:
  - name: grafana-agent
    repo: https://grafana.github.io/helm-charts
    version: 0.40.0
    releaseName: grafana-agent
    namespace: monitoring
    valuesInline:
      agent:
        mode: "flow"

      logs:
        enabled: true

      metrics:
        enabled: true
