namespace: monitoring

helmCharts:
  - name: grafana
    repo: https://grafana.github.io/helm-charts
    version: 7.3.7
    releaseName: grafana
    namespace: monitoring
    valuesInline:
      adminPassword: admin

      service:
        type: NodePort
        nodePort: 32000
