namespace: cert-manager

helmGlobals:
  chartHome: /tmp/helmcharts

resources:
  - cluster-issuer.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.14.4
    releaseName: cert-manager
    namespace: cert-manager
    valuesInline:
      installCRDs: true
