namespace: monitoring

helmGlobals:
  chartHome: /tmp/helmcharts

helmCharts:
  - name: loki
    repo: https://grafana.github.io/helm-charts
    version: 5.43.0
    releaseName: loki
    namespace: monitoring
    valuesInline:
      loki:
        persistence:
          enabled: false
      write:
        persistence:
          volumeClaimsEnabled: false
      read:
        persistence:
          volumeClaimsEnabled: false
      backend:
        persistence:
          volumeClaimsEnabled: false
      monitoring:
        selfMonitoring:
          enabled: false
          grafanaAgent:
            installOperator: false
      test:
        enabled: false
