namespace: monitoring

helmGlobals:
  chartHome: /tmp/helmcharts

helmCharts:
  - name: loki
    repo: https://grafana.github.io/helm-charts
    version: 5.43.0
    releaseName: loki
    namespace: monitoring
    valuesInline:
      singleBinary:
        replicas: 1
        persistence:
          enabled: false
        extraVolumes:
          - name: storage
            emptyDir: {}
        extraVolumeMounts:
          - name: storage
            mountPath: /var/loki
      write:
        replicas: 0
        persistence:
          volumeClaimsEnabled: false
      read:
        replicas: 0
        persistence:
          volumeClaimsEnabled: false
      backend:
        replicas: 0
        persistence:
          volumeClaimsEnabled: false
      monitoring:
        selfMonitoring:
          enabled: false
          grafanaAgent:
            installOperator: false
        lokiCanary:
          enabled: false
      test:
        enabled: false
