apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: infra
  source:
    repoURL: https://github.com/tekne-ops/gitops-platform
    targetRevision: main
    path: infrastructure/alloy-crds/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - Replace=true
