apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/tekne-opsadvise/gitops-platform
    path: infrastructure
  project: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true