apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - projects.yaml
  - namespaces.yaml
  - prometheus-operator-crds.yaml
  - cert-manager.yaml
  - ingress-nginx.yaml
  - loki.yaml
  - kube-prometheus-stack.yaml
  - k8s-monitoring.yaml
  - devops-lab.yaml
